module Mtg::Card
  FRAME_EFFECTS = [
    "colorshifted",
    "companion",
    "compasslanddfc",
    "convertdfc",
    "devoid",
    "draft",
    "etched",
    "extendedart",
    "fandfc",
    "fullart",
    "inverted",
    "legendary",
    "lesson",
    "miracle",
    "mooneldrazidfc",
    "nyxtouched",
    "originpwdfc",
    "shatteredglass",
    "showcase",
    "snow",
    "sunmoondfc",
    "textless",
    "tombstone",
    "upsidedowndfc",
    "waxingandwaningmoondfc",
  ]

  enum FrameEffects
    ColorShifted
    Companion
    CompassLandDFC
    Convertdfc
    Devoid
    Draft
    Etched
    ExtendedArt
    Fandfc
    FullArt
    Inverted
    Legendary
    Lesson
    Miracle
    MoonEldraziDFC
    NyxTouched
    OriginPwDFC
    Shatteredglass
    Showcase
    Snow
    SunMoonDFC
    Textless
    Tombstone
    Upsidedowndfc
    WaxingAndWaningMoonDFC
  end
end
