module Mtg::Card
  PROMO_TYPES = [
    "alchemy",
    "arenaleague",
    "boosterfun",
    "boxtopper",
    "brawldeck",
    "bringafriend",
    "bundle",
    "buyabox",
    "commanderparty",
    "concept",
    "confettifoil",
    "convention",
    "datestamped",
    "dossier",
    "doublerainbow",
    "draculaseries",
    "draftweekend",
    "duels",
    "embossed",
    "event",
    "fnm",
    "galaxyfoil",
    "gameday",
    "giftbox",
    "gilded",
    "glossy",
    "godzillaseries",
    "halofoil",
    "instore",
    "intropack",
    "invisibleink",
    "jpwalker",
    "judgegift",
    "league",
    "magnified",
    "mediainsert",
    "moonlitland",
    "neonink",
    "oilslick",
    "openhouse",
    "planeswalkerstamped",
    "plastic",
    "playerrewards",
    "playpromo",
    "poster",
    "premiereshop",
    "prerelease",
    "promopack",
    "rainbow",
    "raisedfoil",
    "ravnicacity",
    "rebalanced",
    "release",
    "schinesealtart",
    "scroll",
    "serialized",
    "setextension",
    "setpromo",
    "silverfoil",
    "stamped",
    "starterdeck",
    "stepandcompleat",
    "storechampionship",
    "surgefoil",
    "textured",
    "themepack",
    "thick",
    "tourney",
    "vault",
    "wizardsplaynetwork",
  ]

  enum PromoTypes
    Alchemy
    ArenaLeague
    BoosterFun
    BoxTopper
    BrawlDeck
    Bringafriend
    Bundle
    BuyABox
    Commanderparty
    Concept
    Confettifoil
    Convention
    DateStamped
    Dossier
    Doublerainbow
    Draculaseries
    DraftWeekend
    Duels
    Embossed
    Event
    FNM
    Galaxyfoil
    Gameday
    Giftbox
    Gilded
    Glossy
    GodzillaSeries
    Halofoil
    InStore
    IntroPack
    Invisibleink
    JpWalker
    JudgeGift
    League
    Magnified
    MediaInsert
    Moonlitland
    Neonink
    Oilslick
    OpenHouse
    PlaneswalkerStamped
    Plastic
    PlayerRewards
    Playpromo
    Poster
    PremiereShop
    PreRelease
    PromoPack
    Rainbow
    Raisedfoil
    Ravnicacity
    Rebalanced
    Release
    Schinesealtart
    Scroll
    Serialized
    Setextension
    SetPromo
    Silverfoil
    Stamped
    Starterdeck
    Stepandcompleat
    Storechampionship
    Surgefoil
    Textured
    ThemePack
    Thick
    Tourney
    Vault
    WizardsPlayNetwork
  end
end
