module Mtg::Card
  PROMO_TYPES = [
    "arenaleague",
    "boosterfun",
    "boxtopper",
    "brawldeck",
    "bundle",
    "buyabox",
    "convention",
    "datestamped",
    "draftweekend",
    "duels",
    "event",
    "fnm",
    "gameday",
    "gateway",
    "giftbox",
    "godzillaseries",
    "instore",
    "intropack",
    "jpwalker",
    "judgegift",
    "league",
    "mediainsert",
    "openhouse",
    "planeswalkerstamped",
    "playerrewards",
    "premiereshop",
    "prerelease",
    "promopack",
    "release",
    "setpromo",
    "stamped",
    "themepack",
    "tourney",
    "wizardsplaynetwork",
  ]

  enum PromoTypes
    ArenaLeague
    BoosterFun
    BoxTopper
    BrawlDeck
    Bundle
    BuyABox
    Convention
    DateStamped
    DraftWeekend
    Duels
    Event
    FNM
    Gameday
    Gateway
    Giftbox
    GodzillaSeries
    InStore
    IntroPack
    JpWalker
    JudgeGift
    League
    MediaInsert
    OpenHouse
    PlaneswalkerStamped
    PlayerRewards
    PremiereShop
    PreRelease
    PromoPack
    Release
    SetPromo
    Stamped
    ThemePack
    Tourney
    WizardsPlayNetwork
  end
end
