module Mtg::Card
  WATERMARK = [
    "abzan",
    "agentsofsneak",
    "arena",
    "atarka",
    "azorius",
    "boros",
    "colorpie",
    "conspiracy",
    "corocoro",
    "crossbreedlabs",
    "d&d",
    "dci",
    "dengekimaoh",
    "dimir",
    "dromoka",
    "flavor",
    "fnm",
    "foretell",
    "goblinexplosioneers",
    "golgari",
    "grandprix",
    "gruul",
    "herospath",
    "izzet",
    "japanjunior",
    "jeskai",
    "judgeacademy",
    "junior",
    "juniorapac",
    "junioreurope",
    "kolaghan",
    "leagueofdastardlydoom",
    "lorehold",
    "mardu",
    "mirran",
    "mlpgems",
    "mlpsparkle",
    "mlpwaningmoon",
    "mps",
    "mtg",
    "mtg10",
    "mtg15",
    "nerf",
    "ojutai",
    "orderofthewidget",
    "orzhov",
    "phyrexian",
    "planeswalker",
    "prismari",
    "protour",
    "quandrix",
    "rakdos",
    "scholarship",
    "selesnya",
    "set",
    "set (5DN)",
    "set (AER)",
    "set (AKH)",
    "set (ALA)",
    "set (ALL)",
    "set (APC)",
    "set (ARB)",
    "set (ARN)",
    "set (ATQ)",
    "set (AVR)",
    "set (BFZ)",
    "set (BNG)",
    "set (BOK)",
    "set (C13)",
    "set (C14)",
    "set (C15)",
    "set (C16)",
    "set (C17)",
    "set (CHK)",
    "set (CMD)",
    "set (CN2)",
    "set (CNS)",
    "set (CON)",
    "set (CSP)",
    "set (DGM)",
    "set (DIS)",
    "set (DKA)",
    "set (DOM)",
    "set (DRK)",
    "set (DST)",
    "set (DTK)",
    "set (EMN)",
    "set (EVE)",
    "set (EXO)",
    "set (FEM)",
    "set (FRF)",
    "set (FUT)",
    "set (GPT)",
    "set (GRN)",
    "set (GTC)",
    "set (HML)",
    "set (HOU)",
    "set (ICE)",
    "set (INV)",
    "set (ISD)",
    "set (JOU)",
    "set (JUD)",
    "set (KLD)",
    "set (KTK)",
    "set (LEA)",
    "set (LEG)",
    "set (LGN)",
    "set (LRW)",
    "set (M10)",
    "set (M11)",
    "set (M12)",
    "set (M13)",
    "set (M14)",
    "set (M15)",
    "set (M19)",
    "set (MBS)",
    "set (MIR)",
    "set (MMQ)",
    "set (MOR)",
    "set (MRD)",
    "set (NEM)",
    "set (ODY)",
    "set (OGW)",
    "set (ONS)",
    "set (ORI)",
    "set (P02)",
    "set (PC2)",
    "set (PCY)",
    "set (PLC)",
    "set (PLS)",
    "set (POR)",
    "set (PTK)",
    "set (RAV)",
    "set (RIX)",
    "set (RNA)",
    "set (ROE)",
    "set (RTR)",
    "set (S99)",
    "set (SCG)",
    "set (SHM)",
    "set (SOI)",
    "set (SOK)",
    "set (SOM)",
    "set (STH)",
    "set (THS)",
    "set (TMP)",
    "set (TOR)",
    "set (TSP)",
    "set (UDS)",
    "set (ULG)",
    "set (USG)",
    "set (VIS)",
    "set (WTH)",
    "set (WWK)",
    "set (XLN)",
    "set (ZEN)",
    "silumgar",
    "silverquill",
    "simic",
    "sultai",
    "temur",
    "transformers",
    "trumpkatsumai",
    "witherbloom",
    "wotc",
    "wpn",
  ]
end
