module Mtg::Card
  WATERMARKS = [
    "abzan",
    "agentsofsneak",
    "arena",
    "atarka",
    "azorius",
    "boros",
    "brokers",
    "cabaretti",
    "colorpie",
    "conspiracy",
    "corocoro",
    "crossbreedlabs",
    "cutiemark",
    "d&d",
    "dci",
    "dengekimaoh",
    "desparked",
    "dimir",
    "dromoka",
    "flavor",
    "fnm",
    "foretell",
    "goblinexplosioneers",
    "golgari",
    "grandprix",
    "gruul",
    "herospath",
    "izzet",
    "japanjunior",
    "jeskai",
    "judgeacademy",
    "junior",
    "juniorapac",
    "junioreurope",
    "kolaghan",
    "leagueofdastardlydoom",
    "lorehold",
    "maestros",
    "mardu",
    "mirran",
    "mps",
    "mtg",
    "mtg10",
    "mtg15",
    "nerf",
    "obscura",
    "ojutai",
    "orderofthewidget",
    "orzhov",
    "phyrexian",
    "planeswalker",
    "prismari",
    "protour",
    "quandrix",
    "rakdos",
    "riveteers",
    "scholarship",
    "selesnya",
    "set",
    "set (5dn)",
    "set (aer)",
    "set (akh)",
    "set (ala)",
    "set (all)",
    "set (apc)",
    "set (arb)",
    "set (arn)",
    "set (atq)",
    "set (avr)",
    "set (bfz)",
    "set (bng)",
    "set (bok)",
    "set (c13)",
    "set (c14)",
    "set (c15)",
    "set (c16)",
    "set (c17)",
    "set (chk)",
    "set (cmd)",
    "set (cn2)",
    "set (cns)",
    "set (con)",
    "set (csp)",
    "set (dgm)",
    "set (dis)",
    "set (dka)",
    "set (dom)",
    "set (drk)",
    "set (dst)",
    "set (dtk)",
    "set (emn)",
    "set (eve)",
    "set (exo)",
    "set (fem)",
    "set (frf)",
    "set (fut)",
    "set (gpt)",
    "set (grn)",
    "set (gtc)",
    "set (hml)",
    "set (hou)",
    "set (ice)",
    "set (inv)",
    "set (isd)",
    "set (jou)",
    "set (jud)",
    "set (kld)",
    "set (ktk)",
    "set (lea)",
    "set (leg)",
    "set (lgn)",
    "set (lrw)",
    "set (m10)",
    "set (m11)",
    "set (m12)",
    "set (m13)",
    "set (m14)",
    "set (m15)",
    "set (m19)",
    "set (mbs)",
    "set (mir)",
    "set (mmq)",
    "set (mor)",
    "set (mrd)",
    "set (nem)",
    "set (nph)",
    "set (ody)",
    "set (ogw)",
    "set (ons)",
    "set (ori)",
    "set (p02)",
    "set (pc2)",
    "set (pcy)",
    "set (plc)",
    "set (pls)",
    "set (por)",
    "set (ptk)",
    "set (rav)",
    "set (rix)",
    "set (rna)",
    "set (roe)",
    "set (rtr)",
    "set (s99)",
    "set (scg)",
    "set (shm)",
    "set (soi)",
    "set (sok)",
    "set (som)",
    "set (sth)",
    "set (ths)",
    "set (tmp)",
    "set (tor)",
    "set (tsp)",
    "set (uds)",
    "set (ulg)",
    "set (usg)",
    "set (vis)",
    "set (wth)",
    "set (wwk)",
    "set (xln)",
    "set (zen)",
    "silumgar",
    "silverquill",
    "simic",
    "sultai",
    "tarkir",
    "temur",
    "transformers",
    "trumpkatsumai",
    "witherbloom",
    "wotc",
    "wpn",
  ]
end
