module Mtg::Product
  SUBTYPES = [
    "advanced",
    "archenemy",
    "battle_pack",
    "brawl",
    "challenge",
    "challenger",
    "championship",
    "clash",
    "collector",
    "collectors_edition",
    "commander",
    "commander_collection",
    "convention_exclusive",
    "deck_builders_toolkit",
    "default",
    "draft",
    "draft_set",
    "duel",
    "event",
    "fat_pack",
    "from_the_vault",
    "game_night",
    "gift_bundle",
    "guild_kit",
    "intro",
    "jumpstart",
    "land_station",
    "other",
    "planechase",
    "planeswalker",
    "play",
    "premium",
    "prerelease_kit",
    "promotional",
    "sealed_set",
    "secret_lair",
    "secret_lair_bundle",
    "set",
    "six-card",
    "spellbook",
    "starter_deck",
    "theme",
    "topper",
    "tournament_deck",
    "two_player_starter",
    "unknown",
    "welcome",
  ]

  enum Subtype
    Advanced
    Archenemy
    BattlePack
    Brawl
    Challenge
    Challenger
    Championship
    Clash
    Collector
    CollectorsEdition
    Commander
    CommanderCollection
    ConventionExclusive
    DeckBuildersToolkit
    Default
    Draft
    DraftSet
    Duel
    Event
    FatPack
    FromTheVault
    GameNight
    GiftBundle
    GuildKit
    Intro
    Jumpstart
    LandStation
    Other
    Planechase
    Planeswalker
    Play
    Premium
    PrereleaseKit
    Promotional
    SealedSet
    SecretLair
    SecretLairBundle
    Set
    SixCard
    Spellbook
    StarterDeck
    Theme
    Topper
    TournamentDeck
    TwoPlayerStarter
    Unknown
    Welcome
  end
end
