module Mtg::Product
  SUBTYPES = [
    "advanced",
    "archenemy",
    "battle_pack",
    "challenge",
    "clash",
    "collector",
    "deck_builders_toolkit",
    "default",
    "deluxe",
    "event",
    "from_the_vault",
    "intro",
    "jumpstart",
    "minimal_packaging",
    "planechase",
    "planeswalker",
    "premium",
    "secret_lair",
    "set",
    "spellbook",
    "starter",
    "theme",
    "topper",
    "vip",
  ]

  enum Subtype
    Advanced
    Archenemy
    BattlePack
    Challenge
    Clash
    Collector
    DeckBuildersToolkit
    Default
    Deluxe
    Event
    FromTheVault
    Intro
    Jumpstart
    MinimalPackaging
    Planechase
    Planeswalker
    Premium
    SecretLair
    Set
    Spellbook
    Starter
    Theme
    Topper
    Vip
  end
end
