module Mtg::Deck
  TYPES = [
    "advanced deck",
    "advanced pack",
    "archenemy deck",
    "arena promotional deck",
    "arena starter deck",
    "arena starter kit",
    "basic deck",
    "box set",
    "brawl deck",
    "challenger deck",
    "clash pack",
    "commander deck",
    "duel deck",
    "duel of the planeswalkers deck",
    "event deck",
    "game night deck",
    "guild kit",
    "halfdeck",
    "intro pack",
    "jumpstart",
    "mtgo theme deck",
    "pioneer challenger deck",
    "planechase deck",
    "planeswalker deck",
    "premium deck",
    "pro tour deck",
    "secret lair drop",
    "spellslinger starter kit",
    "starter deck",
    "theme deck",
    "welcome booster",
    "welcome deck",
    "world championship deck",
  ]
end
