module Mtg::Deck
  TYPES = [
    "advanced deck",
    "advanced pack",
    "archenemy deck",
    "arena starter kit",
    "basic deck",
    "brawl deck",
    "challenger deck",
    "clash pack",
    "commander deck",
    "duel deck",
    "duel of the planeswalkers deck",
    "event deck",
    "game night deck",
    "guild kit",
    "halfdeck",
    "intro pack",
    "jumpstart",
    "mtgo theme deck",
    "pioneer challenger deck",
    "planechase deck",
    "planeswalker deck",
    "premium deck",
    "spellslinger starter kit",
    "starter deck",
    "theme deck",
    "welcome deck",
    "world championship decks",
  ]
end
