module Mtg::Deck
  TYPES = [
    "advanced deck",
    "advanced pack",
    "archenemy deck",
    "arena promotional deck",
    "arena starter deck",
    "arena starter kit",
    "box set",
    "brawl deck",
    "challenger deck",
    "clash pack",
    "commander deck",
    "deck builder's toolkit",
    "duel deck",
    "duel of the planeswalkers deck",
    "enhanced deck",
    "event deck",
    "game night deck",
    "guild kit",
    "halfdeck",
    "historic brawl precon deck",
    "intro pack",
    "jumpstart",
    "modern event deck",
    "mtgo redemption",
    "mtgo theme deck",
    "pioneer challenger deck",
    "planechase deck",
    "planeswalker deck",
    "premium deck",
    "pro tour deck",
    "sample deck",
    "san diego comic con promos",
    "secret lair drop",
    "shandalar enemy deck",
    "spellslinger starter kit",
    "starter deck",
    "starter kit",
    "theme deck",
    "welcome booster",
    "welcome deck",
    "world championship deck",
  ]
end
