module Mtg::Keywords
  ABILITY_WORDS = [
    "adamant",
    "addendum",
    "alliance",
    "battalion",
    "bloodrush",
    "celebration",
    "channel",
    "chroma",
    "cohort",
    "constellation",
    "converge",
    "corrupted",
    "council's dilemma",
    "coven",
    "delirium",
    "descend",
    "domain",
    "eminence",
    "enrage",
    "fateful hour",
    "fathomless descent",
    "ferocious",
    "formidable",
    "grandeur",
    "hellbent",
    "hero's reward",
    "heroic",
    "imprint",
    "inspired",
    "join forces",
    "kinfall",
    "kinship",
    "landfall",
    "landship",
    "legacy",
    "lieutenant",
    "magecraft",
    "metalcraft",
    "morbid",
    "pack tactics",
    "paradox",
    "parley",
    "radiance",
    "raid",
    "rally",
    "revolt",
    "secret council",
    "spell mastery",
    "strive",
    "sweep",
    "teamwork",
    "tempting offer",
    "threshold",
    "underdog",
    "undergrowth",
    "will of the council",
    "will of the planeswalkers",
  ]
end
