module Mtg::Keywords
  ABILITY_WORDS = [
    "adamant",
    "addendum",
    "alliance",
    "battalion",
    "bloodrush",
    "channel",
    "chroma",
    "cohort",
    "constellation",
    "converge",
    "corrupted",
    "council's dilemma",
    "coven",
    "delirium",
    "domain",
    "eminence",
    "enrage",
    "fateful hour",
    "ferocious",
    "formidable",
    "grandeur",
    "hellbent",
    "hero's reward",
    "heroic",
    "imprint",
    "inspired",
    "join forces",
    "kinfall",
    "kinship",
    "landfall",
    "landship",
    "legacy",
    "lieutenant",
    "magecraft",
    "metalcraft",
    "morbid",
    "pack tactics",
    "parley",
    "radiance",
    "raid",
    "rally",
    "revolt",
    "secret council",
    "spell mastery",
    "strive",
    "sweep",
    "teamwork",
    "tempting offer",
    "threshold",
    "underdog",
    "undergrowth",
    "will of the council",
  ]
end
