module Mtg::Keywords
  KEYWORD_ABILITIES = [
    "absorb",
    "affinity",
    "afflict",
    "afterlife",
    "aftermath",
    "amplify",
    "annihilator",
    "ascend",
    "assist",
    "augment",
    "aura swap",
    "awaken",
    "backup",
    "banding",
    "bargain",
    "basic landcycling",
    "battle cry",
    "bestow",
    "blitz",
    "bloodthirst",
    "boast",
    "bushido",
    "buyback",
    "cascade",
    "casualty",
    "champion",
    "changeling",
    "choose a background",
    "cipher",
    "cleave",
    "commander ninjutsu",
    "companion",
    "compleated",
    "conspire",
    "convoke",
    "craft",
    "crew",
    "cumulative upkeep",
    "cycling",
    "dash",
    "daybound",
    "deathtouch",
    "decayed",
    "defender",
    "delve",
    "demonstrate",
    "desertwalk",
    "dethrone",
    "devoid",
    "devour",
    "disguise",
    "disturb",
    "doctor's companion",
    "double agenda",
    "double strike",
    "double team",
    "dredge",
    "echo",
    "embalm",
    "emerge",
    "enchant",
    "encore",
    "enlist",
    "entwine",
    "epic",
    "equip",
    "escalate",
    "escape",
    "eternalize",
    "evoke",
    "evolve",
    "exalted",
    "exhaust",
    "exploit",
    "extort",
    "fabricate",
    "fading",
    "fear",
    "firebending",
    "first strike",
    "flanking",
    "flash",
    "flashback",
    "flying",
    "for mirrodin!",
    "forecast",
    "forestcycling",
    "forestwalk",
    "foretell",
    "fortify",
    "freerunning",
    "frenzy",
    "friends forever",
    "fuse",
    "gift",
    "graft",
    "gravestorm",
    "harmonize",
    "haste",
    "haunt",
    "hexproof",
    "hexproof from",
    "hidden agenda",
    "hideaway",
    "horsemanship",
    "impending",
    "improvise",
    "indestructible",
    "infect",
    "ingest",
    "intensity",
    "intimidate",
    "islandcycling",
    "islandwalk",
    "job select",
    "jump-start",
    "kicker",
    "landcycling",
    "landwalk",
    "legendary landwalk",
    "level up",
    "lifelink",
    "living metal",
    "living weapon",
    "madness",
    "max speed",
    "mayhem",
    "megamorph",
    "melee",
    "menace",
    "mentor",
    "miracle",
    "mobilize",
    "modular",
    "more than meets the eye",
    "morph",
    "mountaincycling",
    "mountainwalk",
    "multikicker",
    "mutate",
    "myriad",
    "nightbound",
    "ninjutsu",
    "nonbasic landwalk",
    "offering",
    "offspring",
    "outlast",
    "overload",
    "partner",
    "partner with",
    "persist",
    "phasing",
    "plainscycling",
    "plainswalk",
    "poisonous",
    "protection",
    "prototype",
    "provoke",
    "prowess",
    "prowl",
    "rampage",
    "ravenous",
    "reach",
    "read ahead",
    "rebound",
    "reconfigure",
    "recover",
    "reinforce",
    "renown",
    "replicate",
    "retrace",
    "riot",
    "ripple",
    "saddle",
    "scavenge",
    "shadow",
    "shroud",
    "skulk",
    "slivercycling",
    "sneak",
    "solved",
    "soulbond",
    "soulshift",
    "specialize",
    "spectacle",
    "splice",
    "split second",
    "spree",
    "squad",
    "station",
    "storm",
    "sunburst",
    "surge",
    "suspend",
    "swampcycling",
    "swampwalk",
    "tiered",
    "toxic",
    "training",
    "trample",
    "transfigure",
    "transmute",
    "tribute",
    "typecycling",
    "umbra armor",
    "undaunted",
    "undying",
    "unearth",
    "unleash",
    "vanishing",
    "vigilance",
    "ward",
    "warp",
    "web-slinging",
    "wither",
    "wizardcycling",
  ]
end
