module Mtg::Keywords
  KEYWORD_ACTIONS = [
    "abandon",
    "activate",
    "adapt",
    "amass",
    "assemble",
    "attach",
    "bolster",
    "cast",
    "clash",
    "cloak",
    "collect evidence",
    "conjure",
    "connive",
    "convert",
    "counter",
    "create",
    "destroy",
    "detain",
    "discard",
    "discover",
    "double",
    "exchange",
    "exert",
    "exile",
    "explore",
    "fateseal",
    "fight",
    "food",
    "goad",
    "incubate",
    "investigate",
    "learn",
    "manifest",
    "meld",
    "mill",
    "monstrosity",
    "open an attraction",
    "planeswalk",
    "play",
    "plot",
    "populate",
    "proliferate",
    "regenerate",
    "reveal",
    "role token",
    "roll to visit your attractions",
    "sacrifice",
    "scry",
    "seek",
    "set in motion",
    "shuffle",
    "support",
    "surveil",
    "suspect",
    "tap",
    "time travel",
    "transform",
    "treasure",
    "untap",
    "venture into the dungeon",
    "vote",
  ]
end
