module Mtg::Keywords
  KEYWORD_ABILITIES = [
    "absorb",
    "affinity",
    "afflict",
    "afterlife",
    "aftermath",
    "amplify",
    "annihilator",
    "ascend",
    "assist",
    "augment",
    "aura swap",
    "awaken",
    "banding",
    "basic landcycling",
    "battle cry",
    "bestow",
    "blitz",
    "bloodthirst",
    "boast",
    "bushido",
    "buyback",
    "cascade",
    "casualty",
    "champion",
    "changeling",
    "cipher",
    "cleave",
    "commander ninjutsu",
    "companion",
    "compleated",
    "conspire",
    "convoke",
    "crew",
    "cumulative upkeep",
    "cycling",
    "dash",
    "daybound",
    "deathtouch",
    "decayed",
    "defender",
    "delve",
    "demonstrate",
    "desertwalk",
    "dethrone",
    "devoid",
    "devour",
    "disturb",
    "double agenda",
    "double strike",
    "dredge",
    "echo",
    "embalm",
    "emerge",
    "enchant",
    "encore",
    "enlist",
    "entwine",
    "epic",
    "equip",
    "escalate",
    "escape",
    "eternalize",
    "evoke",
    "evolve",
    "exalted",
    "exploit",
    "extort",
    "fabricate",
    "fading",
    "fear",
    "first strike",
    "flanking",
    "flash",
    "flashback",
    "flying",
    "forecast",
    "forestcycling",
    "forestwalk",
    "foretell",
    "fortify",
    "frenzy",
    "friends forever",
    "fuse",
    "graft",
    "gravestorm",
    "haste",
    "haunt",
    "hexproof",
    "hexproof from",
    "hidden agenda",
    "hideaway",
    "horsemanship",
    "improvise",
    "indestructible",
    "infect",
    "ingest",
    "intensity",
    "intimidate",
    "islandcycling",
    "islandwalk",
    "jump-start",
    "kicker",
    "landcycling",
    "landwalk",
    "legendary landwalk",
    "level up",
    "lifelink",
    "living metal",
    "living weapon",
    "madness",
    "megamorph",
    "melee",
    "menace",
    "mentor",
    "miracle",
    "modular",
    "more than meets the eye",
    "morph",
    "mountaincycling",
    "mountainwalk",
    "multikicker",
    "mutate",
    "myriad",
    "nightbound",
    "ninjutsu",
    "nonbasic landwalk",
    "offering",
    "outlast",
    "overload",
    "partner",
    "partner with",
    "persist",
    "phasing",
    "plainscycling",
    "plainswalk",
    "poisonous",
    "protection",
    "prototype",
    "provoke",
    "prowess",
    "prowl",
    "rampage",
    "ravenous",
    "reach",
    "read ahead",
    "rebound",
    "reconfigure",
    "recover",
    "reinforce",
    "renown",
    "replicate",
    "retrace",
    "riot",
    "ripple",
    "scavenge",
    "shadow",
    "shroud",
    "skulk",
    "slivercycling",
    "soulbond",
    "soulshift",
    "spectacle",
    "splice",
    "split second",
    "squad",
    "storm",
    "sunburst",
    "surge",
    "suspend",
    "swampcycling",
    "swampwalk",
    "totem armor",
    "training",
    "trample",
    "transfigure",
    "transmute",
    "tribute",
    "typecycling",
    "undaunted",
    "undying",
    "unearth",
    "unleash",
    "vanishing",
    "vigilance",
    "ward",
    "wither",
    "wizardcycling",
  ]
end
