module Mtg::Keywords
  KEYWORD_ACTIONS = [
    "abandon",
    "activate",
    "adapt",
    "amass",
    "assemble",
    "attach",
    "bolster",
    "cast",
    "clash",
    "conjure",
    "connive",
    "convert",
    "counter",
    "create",
    "destroy",
    "detain",
    "discard",
    "double",
    "exchange",
    "exert",
    "exile",
    "explore",
    "fateseal",
    "fight",
    "goad",
    "investigate",
    "learn",
    "manifest",
    "meld",
    "mill",
    "monstrosity",
    "open an attraction",
    "planeswalk",
    "play",
    "populate",
    "proliferate",
    "regenerate",
    "reveal",
    "roll to visit your attractions",
    "sacrifice",
    "scry",
    "seek",
    "set in motion",
    "shuffle",
    "support",
    "surveil",
    "tap",
    "transform",
    "untap",
    "venture into the dungeon",
    "vote",
  ]
end
